// No "server-only" guard here (unlike openrouter.ts): this module is a
// pure function -- no secrets, no I/O, no env var reads -- so there's
// nothing for the guard to protect. Keeping it plain also makes it
// directly unit-testable (the "server-only" package throws
// unconditionally outside Next.js's server bundler, including under
// vitest -- see tests/stubs/server-only-stub.ts for why openrouter.ts
// still needs a resolve alias to be testable at all).

import type { Database } from "../../../types/database";
import type { ProposalContextSummary } from "./proposal-context";
import type { GenerateProposalTextRequest } from "../validation/ai-proposal-text";

type BusinessProfile = Database["public"]["Tables"]["business_profiles"]["Row"];

/**
 * Every rule the model must follow, restated on every call (never
 * "remembered" across requests, since each OpenRouter call is stateless).
 * See docs/10-ai-boundaries.md ("la IA nunca... crea garantías legales")
 * and the brief's explicit "Prompt safety" section. These are safety
 * rules, not style preferences -- they stay fixed regardless of tone/length.
 */
const SAFETY_RULES = `You are drafting text for a home-services contractor's client proposal. Follow these rules exactly:
- Draft professional, client-ready proposal text only.
- Do not claim legal compliance or create legal guarantees of any kind.
- Do not invent a license number, insurance coverage, or bonded status -- only mention these if they are explicitly provided below, and only state exactly what was provided.
- Do not invent a warranty, payment terms, or deposit requirement -- if none is provided below, write neutral, generic language that does not commit to specific numbers, percentages, or durations.
- Do not mention that this text was generated by AI, a language model, or any automated system.
- Do not mention internal system data, database field names, or this application's name.
- Keep language clear, plain, and client-friendly -- avoid legal jargon.
- Use ONLY the facts provided below. Never invent client names, addresses, dates, or amounts not given to you.
- If information needed for a section is missing, write brief, neutral, generally-applicable language instead of leaving it blank or making something up.
- Respond with ONLY a single JSON object matching the exact shape requested -- no markdown, no code fences, no commentary before or after it.`;

const TONE_GUIDANCE: Record<string, string> = {
  professional: "Professional and businesslike, but not stiff or overly formal.",
  friendly: "Warm and approachable, like a contractor who knows their client personally.",
  direct: "Short, plain, no-nonsense sentences. Get to the point.",
  simple: "Very simple words and short sentences, easy for anyone to read quickly.",
  detailed: "Thorough and specific, spelling out particulars rather than staying general.",
};

const LENGTH_GUIDANCE: Record<string, string> = {
  short: "Keep each section brief -- a few sentences at most.",
  standard: "A normal-length paragraph or two per section.",
  detailed: "Multiple paragraphs per section, covering specifics thoroughly.",
};

function fieldOrNeutral(label: string, value: string): string {
  const trimmed = value.trim();
  return trimmed ? `${label}: ${trimmed}` : `${label}: (not provided -- use neutral, generic language)`;
}

function listOrNone(label: string, items: string[]): string {
  return items.length > 0 ? `${label}: ${items.join(", ")}` : `${label}: none`;
}

/**
 * Builds the {system, user} prompt pair sent to OpenRouter. Nothing here
 * ever includes a secret, an API key, or this app's internal ids --
 * proposal/tenant ids are used to SELECT what to summarize, never passed
 * into the prompt text itself.
 */
export function buildProposalTextPrompt(
  request: GenerateProposalTextRequest,
  businessProfile: BusinessProfile,
  proposalContext: ProposalContextSummary
): { system: string; user: string } {
  const tone = request.tone ?? (businessProfile.tone_preference as GenerateProposalTextRequest["tone"]) ?? "professional";

  const featureInstruction =
    request.feature === "all"
      ? 'Draft all three: "terms", "exclusions", and "clientNotes".'
      : request.feature === "terms"
        ? 'Draft only "terms". Leave "exclusions" and "clientNotes" as empty strings.'
        : request.feature === "exclusions"
          ? 'Draft only "exclusions". Leave "terms" and "clientNotes" as empty strings.'
          : 'Draft only "clientNotes". Leave "terms" and "exclusions" as empty strings.';

  const includeInstructions = [
    request.includeWarranty ? "Include a warranty statement in the terms." : "Do not include a warranty statement.",
    request.includePaymentTerms ? "Include payment terms in the terms." : "Do not include payment terms.",
    request.includeExclusions ? "Include a list of exclusions." : "Keep exclusions minimal.",
    request.includeClientResponsibilities
      ? "Include a brief note on client responsibilities in the terms or notes."
      : "Do not mention client responsibilities.",
  ].join(" ");

  const system = [
    SAFETY_RULES,
    `Tone: ${TONE_GUIDANCE[tone] ?? TONE_GUIDANCE.professional}`,
    `Length: ${LENGTH_GUIDANCE[request.length] ?? LENGTH_GUIDANCE.standard}`,
    featureInstruction,
    includeInstructions,
    `Respond with exactly this JSON shape: {"terms": string, "exclusions": string, "clientNotes": string, "warnings": string[]}. "warnings" lists anything you wrote generically because the business profile didn't provide it (e.g. "No warranty policy on file -- used generic language.").`,
  ].join("\n\n");

  const user = [
    "## Business",
    fieldOrNeutral("Business name", businessProfile.business_name),
    fieldOrNeutral("Industry", businessProfile.industry),
    fieldOrNeutral("Main services", businessProfile.main_services),
    fieldOrNeutral("Service area", businessProfile.service_area),
    fieldOrNeutral("License number", businessProfile.license_number),
    fieldOrNeutral("Insurance/bonded statement", businessProfile.insurance_statement),
    fieldOrNeutral("Warranty policy", businessProfile.default_warranty_policy),
    fieldOrNeutral("Payment terms", businessProfile.default_payment_terms),
    fieldOrNeutral("Deposit policy", businessProfile.default_deposit_policy),
    fieldOrNeutral("Change order policy", businessProfile.default_change_order_policy),
    fieldOrNeutral("Cancellation/rescheduling policy", businessProfile.default_cancellation_policy),
    fieldOrNeutral("Cleanup policy", businessProfile.default_cleanup_policy),
    fieldOrNeutral("Materials policy", businessProfile.default_materials_policy),
    fieldOrNeutral("Client responsibilities", businessProfile.default_client_responsibilities),
    fieldOrNeutral("Standard exclusions", businessProfile.default_exclusions),
    "",
    "## This proposal",
    fieldOrNeutral("Proposal title", proposalContext.proposalTitle),
    fieldOrNeutral("Service type", proposalContext.customServiceName || proposalContext.serviceType),
    fieldOrNeutral("Client name (for a personalized greeting only, do not invent details about them)", proposalContext.clientDisplayName ?? ""),
    fieldOrNeutral("Scope summary", proposalContext.scopeSummary ?? ""),
    fieldOrNeutral("Scope introduction", proposalContext.scopeIntro ?? ""),
    listOrNone("Scope sections", proposalContext.sectionTitles),
    listOrNone("Measurements taken", proposalContext.measurementNames),
    listOrNone("Labor items", proposalContext.laborLabels),
    listOrNone("Material categories", proposalContext.materialCategories),
  ].join("\n");

  return { system, user };
}
